- ai/CosyVoice/cosyvoice/cli/cosyvoice.py
- ai/CosyVoice/main.py
- ai/CosyVoice/services/s3_service.py
- ai/CosyVoice/services/tts_service.py
Closes #16
---
#16 의 comment에서 언급하였던 것처럼, 사용자가 생성한 보이스팩을 통해 생성한 음성을 들어볼 수 있도록 하였습니다.
이때 기존처럼 generated_audio/에 있는 것이 아닌, speakers/{voicepackId}/sample_test.wav 로 저장하여 추후 사용하는 데에 용이하도록 변경하였습니다.
생성한 음성을 저장하는 함수인 save_audio 를 추가하여,
file_path를 지정하면 해당 경로로 음성파일을 저장하는 구조를 구축하였습니다.
---
---
---
---
> feat: 보이스팩 생성 시 샘플 음성을 features에 저장하는 기능 추가

- backend/build.gradle.kts
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/config/SwaggerConfig.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/config/WebConfig.kt
Closes #
---
AWS RDS 사용을 위해 application.yml 파일 수정 후 github secrets에 등록하였고
build.gradle에 mysql 관련 implementation 추가하였습니다.
배포환경에서 swagger가 동작하지 않는 이슈가 있었는데
로컬용, 배포용 swagger Server를 나누어 두 환경 모두에서 swagger 동작 테스트 완료하였습니다.
---
---
---
---
> chore: RDS 연결을 위한 설정 파일 변경

- .gitmodules
Closes #
---
chore: Delete .gitmodules
---
---
---
---
> chore: Delete .gitmodules

- test.txt
Closes #
---
chore: Delete test.txt
---
---
---
---
> chore: Delete test.txt

- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/service/VoicepackCallbackService.kt
- 주석 처리된 생성 콜백 처리 로직 활성화
Closes #
---
* 테스트용으로 주석처리되어 비활성화된 보이스팩 생성 콜백 메시지 처리 기능 재활성화
---
---
---
---
> fix: VoicepackCallbackService에서 생성 콜백 처리 로직 활성화

- AI/main.py
---
Cloud Run 특성상, Background Task를 통해 진행한 작업이 인스턴스로 진행된다는 보장이 없어,
현재와 같은 방향으로 진행할 때 Background에서 작업이 진행되는 중 인스턴스가 해지되는 경우가 발생할 수 있다고 합니다.(@miniwa00)
종민님과의 대화 이후, 보이스팩 생성과 음성 합성 작업을 비동기에서 동기로 넘기기로 하였고, 그에 따라 response의 status를 기존 202에서 200으로 바꾸게 되었습니다. 이 점은 확인해주시면 되겠습니다. (@Ready-Bridge)
---
---
---
---
> feat: 보이스팩 생성 및 음성 합성 동기화 작업 수행

- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/notification/NotificationService.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/VoicepackController.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/VoicepackService.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/convert/VoicepackConvertRequest.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/convert/VoicepackConvertRequestRepository.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/convert/dto/VoicepackConvertRequestDto.kt
Closes #
---
- **보이스팩 변환 요청 상태 확인 `GET /api/voicepack/convert/status/{id}`**
- 음성 합성 과정과 동일하게 **보이스팩 변환 요청** 시에도 현재 요청의 **진행 상태**를 확인할 수 있는 API를 구현하였습니다.
requestId를 담아 요청을 보내게되면 PENDING, PROCESSING, COMPLETED, FAILED의 상태 정보를 반환해주는 구조입니다.
- 음성 합성과 다르게 presigned url이 필요하지 않아 제외하였고 기존의 VoicepackRequest 네이밍을 조금 더 직관적으로 VoicepackConvertRequest로 수정하였습니다.
- 음성 합성과 동일하게 error_message를 Entity에 추가하여 함께 반환을 해주려고 했지만 DB 스키마를 변경해야하기에 추후 전체 리팩토링 과정에서 이 부분 진행하도록 하겠습니다.
---
---
---
---
> feat: 보이스팩 변환 상태 조회 API 추가 및 관련 DTO 구현

- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/Voicepack.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/VoicepackController.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/VoicepackService.kt
Closes #
---
`DELETE /api/voicepack/{voicepackId}`로 보이스팩을 삭제합니다.
- 작업 이후 실제 데이터 삭제 여부와 상관없이 `204 No Content`를 반환합니다 (멱등성)
연관된 데이터인 음성 합성 요청과 보이스팩 이용권 정보도 CASCADE로 삭제합니다.
---
> feat: 보이스팩 삭제 API 및 서비스 메서드 추가 (관련 엔티티에 CASCADE 처리)

- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/credit/service/CreditService.kt
Closes #
---
- getUserBalance 메서드의 `@Transactional` 어노테이션을 `readOnly=false`로 변경하여 크레딧 잔액 조회 시 크레딧 데이터가 없는 경우 데이터 추가가 가능하도록 수정함.
---
---
---
---
> hotfix: 크레딧 잔액 조회 메서드의 트랜잭션 설정 변경

- AI/config/settings.py
- AI/main.py
- AI/utils/sqs_handler.py
- AI/utils/synthesis_handler.py
- AI/utils/voice_synthesizer.py
Closes #85 
---
AI 비서용 음성 합성 엔드포인트를 새로 생성하였습니다. 이제 해당 엔드포인트로 오는 요청을 처리할 수 있으며 이는 기존 음성 합성 로직과 같은 매커니즘으로 진행됩니다. 저장소의 위치만 달라졌습니다.
긴 문장에서 한 번에 합성하는 것이 성능이 잘 나오지 않는 것을 발견하여, 현재는 AI 비서용 텍스트의 첫 문장만 음성 합성을 진행하도록 임시조치 해놓은 상태입니다.
빠른 시일 내에 긴 문장에 대한 음성 합성에 대한 이슈 발행 및 해결 예정입니다.
---
---
---
---
> feat: AI 비서용 음성 합성 엔드포인트 생성

- AI/config/settings.py
- AI/utils/voice_synthesizer.py
- AI/zonos/model.py
Closes #122 
---
Zonos의 공식 레포지토리에 올라온 PR 중 infinite streaming이라는 PR을 구현한 뒤 저희 코드에 적용하였습니다.
이제 문장과 문장 사이의 연결이 더 부드럽고 자연스럽게 이어지는 효과를 기대할 수 있습니다.
---
---
---
---
> fix: 합성된 문장 사이 연결하는 부분 개선

- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/aiAssistant/controller/AiAssistantController.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/aiAssistant/dto/request/synthesis/AiAssistantSynthesisSubmitRequest.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/aiAssistant/service/AiAssistantService.kt
Closes #50 
---
AI 비서 이용하기 요청 시 불필요한 voicepackId를 받고 있어 해당 내용 수정하였습니다.
또한, 테스트용 시간대를 삭제하였는데 현재 EventBridge 이슈로 인해 다시 테스트용 시간대를 추가하였습니다.
---
---
---
---
> refactor: AI 비서 이용하기 시 voicepackId 요청 로직 제거

- frontend/src/components/common/SelectBox.js
- frontend/src/components/common/VoicePackModal.js
- frontend/src/pages/ai-assistant/AssistantSetup.js
- frontend/src/pages/mypage/MyDashboard.js
- frontend/src/pages/mypage/MyRevenue.js
- frontend/src/pages/mypage/MyVoicepacks.js
Closes #132
---
사용자는 보유한 보이스팩과 명언 카테고리(한국/동양/서양)를 선택하고, 오늘의 감정을 텍스트로 입력합니다.
입력된 감정 텍스트를 바탕으로, 백엔드에서 적절한 명언 문구를 자동 추천합니다.
추천된 명언은 사용자가 선택한 보이스팩을 통해 TTS 음성으로 변환되어 재생됩니다.
생성하기 버튼 클릭 시, 백엔드에서 명언 추천 및 음성 합성 요청이 수행됩니다.
응답으로 전달되는 Location 헤더의 polling URL을 이용하여, TTS 변환 상태를 주기적으로 확인합니다.
변환 완료 시, BasicVoice와 동일하게 오디오 재생 및 다운로드 가능한 형태로 표시됩니다.
보이스 생성 시, 이름에 특수기호가 포함되면 디렉토리 경로가 깨지거나 오류 발생 가능성이 있음
이를 방지하기 위해, 보이스 이름에 특수기호가 포함될 경우 음성 생성을 차단하도록 구현함
알림창을 통해 사용자에게 입력 제한 안내
---
---
---
---
> feat: 명언 생성 구현 & 보이스 생성 이름 특수기호 제외

- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/quote/QuoteService.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/VoicepackService.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/dto/VoicepackSynthesisReqRes.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/voicepack/synthesis/VoiceSynthesisRequest.kt
#144 
---
- 음성 합성 요청에 감정 인덱스 추가 및 관련 데이터 클래스 수정
- 관련 dto 및 요청 필드에 정보 추가
---
---
---
---
> feat: 음성 합성 요청에 감정 인덱스 추가 및 관련 데이터 클래스 수정

- AI/main.py
- AI/utils/synthesis_handler.py
- AI/utils/voice_synthesizer.py
#144 
---
베이직 보이스에 emotionIndex를 요청받도록 설정하였고,
내부 합성 로직에서 이 emotionIndex를 사용해 합성에 감정을 이용하는 것으로 진행했습니다.
이때 샘플보이스나 AI비서, 명언에는 감정을 사용하지 않으므로 이를 default값인 0으로 설정하였고,
베이직 보이스에서 들어오는 감정 인덱스만 지정해주는 방식으로 구현했습니다.
---
---
---
---
> feat: 베이직 보이스에 감정 인덱스 매개변수 추가 및 관련 로직 수정

- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/aiAssistant/controller/AiAssistantController.kt
- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/aiAssistant/service/AiAssistantService.kt
Closes #
---
AI 비서 세팅 시 사용 권한이 없는 보이스팩도 설정이 되는 경우가 있어 예외 처리를 추가하였습니다.
---
---
---
---
> feat: AI 비서 세팅 시 사용 권한 없는 보이스팩 예외 처리 추가

- lambda/ai_assistant_lambda.py
- lambda/bbcnews/lambda_function.py
- lambda/googlenews/lambda_function.py
- lambda/itnews/lambda_function.py
- lambda/register_speaker_lambda.py
- lambda/synthesize_lambda.py
Closes #
---
Cloud Run 자체적으로 cold start 시에 도착한 요청을 보관하고있다가 처리하고 있는데 
기존 Cloud Run 요청 람다에서는 timeout이 발생하면 unacked message로 MQ에 다시 남게되어 cold start 가 끝나고 해당 요청이 성공 할 때 까지 람다가 계속 트리거 후 중복 요청을 보내는 문제점이 있었습니다.
완벽한 방식은 아니지만 현재는 람다가 timeout(10초로 설정하였음) 오류와 별개로 무조건 요청을 한 번 만 보내고 종료하도록 로직을 수정 하였습니다.
이 부분은 추후 더 좋은 방식으로 리팩토링을 고려하는 것이 좋을 것 같습니다.
---
---
---
---
> feat: Cloud Run 모델 요청 람다 로직 구현

- backend/src/main/kotlin/kr/ac/kookmin/cs/capstone/voicepack_platform/aiAssistant/enums/Categories.kt
Closes #
---
AI 비서의 카테고리에 경제, 스포츠를 추가하였습니다.
---
---
---
---
> feat: AI 비서 카테고리(경제, 스포츠) 추가

- frontend/src/components/common/VoicePack.js
- frontend/src/components/common/VoicePackModal.js
- frontend/src/components/layout/Sidebar.js
- frontend/src/hooks/useSignin.js
- frontend/src/hooks/useVoicepackUsage.js
- frontend/src/pages/Quote.js
- frontend/src/pages/RememberVoice.js
- frontend/src/pages/VoiceCreate.js
- frontend/src/pages/VoiceStore.js
Closes #
---
- 401 상태: `비밀번호가 틀렸습니다.` 메시지 출력
- 400 상태: `존재하지 않는 이메일이거나 형식이 올바르지 않습니다.` 메시지 출력
- 보유한 보이스팩 조회 시 `isVideoBased === true`인 보이스팩 제외
- 작성자 이메일(author) 대신 이름(authorName)으로 표기
- 보이스팩 이름이 긴 경우 `truncate(...)` 처리로 레이아웃 깨짐 방지
- 보이스팩 생성 섹션 내 성별·카테고리 입력 UI 정렬
- 기능 명칭 “명언 생성” → **“오늘의 명언”** 으로 수정
---
---
---
---
> fix: 로그인 오류 메시지 처리 및 보이스팩 UI/필터링 개선

- docs/pages/lambda.md
> docs: Lambda 관련 docs 작성

- docs/pages/lambda.md
> Docs lambda

- docs/pages/lambda.md
> docs: lambda docs 제목 수정

- docs/pages/lambda.md
> docs: lambda docs 제목 한글로 수정

- lambda/bbcnews/lambda_function.py
- lambda/economy/lambda_function.py
- lambda/itnews/lambda_function.py
- lambda/sports/lambda_function.py
feat: 경제, 스포츠 추가. 뉴스 헤드라인 수를 5에서 3으로 변경
> feat: 경제, 스포츠 추가. 뉴스 헤드라인 수를 5에서 3으로 변경
